// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: observer_directory.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createObserverDirectorySnapshot = `-- name: CreateObserverDirectorySnapshot :one
WITH hours AS MATERIALIZED (
 SELECT g.h, coalesce(r.status, 'missing') AS status
 FROM generate_series($1::timestamptz, $2::timestamptz - interval '1 hour', interval '1 hour') g(h)
 LEFT JOIN analytics_rollup_hours r ON r.hour = g.h
), coverage AS (
 SELECT count(*)::integer AS expected,
        count(*) FILTER (WHERE status = 'complete')::integer AS complete,
        count(*) FILTER (WHERE status = 'partial')::integer AS partial,
        count(*) FILTER (WHERE status = 'missing')::integer AS missing
 FROM hours
), candidates AS MATERIALIZED (
 SELECT o.id, o.display_name, o.observer_type,
        coalesce(o.last_iata, '')::text AS iata,
        CASE WHEN greatest(coalesce(o.last_status_at, o.last_seen), o.last_seen) > now() - interval '5 minutes'
             THEN 'online' ELSE 'offline' END AS status,
        CASE WHEN o.radio_freq_mhz IS NOT NULL AND o.radio_bw_khz IS NOT NULL AND o.radio_sf IS NOT NULL
             THEN concat(o.radio_freq_mhz, ',', o.radio_bw_khz, ',', o.radio_sf) END AS radio,
        coalesce((SELECT jsonb_agg(ts.name ORDER BY ts.name) FROM observer_scopes os JOIN transport_scopes ts ON ts.id = os.scope_id WHERE os.observer_id = o.id), '[]'::jsonb) AS scopes
 FROM observers o
 WHERE NOT $12::boolean AND (coalesce(cardinality($3::bpchar[]), 0) = 0 OR o.last_iata = ANY($3::bpchar[]))
   AND ($4::text = '' OR EXISTS (SELECT 1 FROM observer_brokers ob WHERE ob.observer_id = o.id AND ob.broker_name = $4))
   AND ($5::text = '' OR o.display_name ILIKE '%' || $5 || '%')
   AND ($6::text = '' OR CASE WHEN greatest(coalesce(o.last_status_at, o.last_seen), o.last_seen) > now() - interval '5 minutes' THEN 'online' ELSE 'offline' END = $6)
   AND ($7::text = '' OR EXISTS (SELECT 1 FROM observer_scopes os JOIN transport_scopes ts ON ts.id = os.scope_id WHERE os.observer_id = o.id AND ts.name = $7))
), traffic AS (
 SELECT a.observer_id, sum(a.observation_count)::bigint AS observations
 FROM analytics_hourly_observer_identity a
 JOIN hours h ON h.h = a.hour AND h.status = 'complete'
 JOIN candidates c ON c.id = a.observer_id
 WHERE (coalesce(cardinality($3::bpchar[]), 0) = 0 OR a.iata = ANY($3::bpchar[]))
 GROUP BY a.observer_id
), listed AS (
 SELECT c.id, c.display_name, c.observer_type, c.iata, c.status, c.radio, c.scopes, CASE WHEN v.complete = v.expected THEN coalesce(t.observations, 0) END AS observations
 FROM candidates c CROSS JOIN coverage v LEFT JOIN traffic t ON t.observer_id = c.id
 WHERE $8::text = '' OR c.observer_type = $8
), packed AS (
 SELECT coalesce(jsonb_agg(
   jsonb_strip_nulls(jsonb_build_object('id', id, 'displayName', display_name, 'observerType', observer_type, 'iata', iata, 'status', status, 'radio', radio, 'scopes', scopes))
   || jsonb_build_object('observationCount', observations)
   ORDER BY CASE WHEN $9::text = 'traffic' THEN observations END DESC NULLS LAST,
            lower(coalesce(display_name, '')) COLLATE "C", id
 ), '[]'::jsonb) AS items, max(observations) AS maximum
 FROM listed
)
INSERT INTO observer_directory_snapshots (id, query_key, metadata, items)
SELECT $10, $11,
 jsonb_build_object(
   'windowStart', (extract(epoch FROM $1::timestamptz)*1000)::bigint,
   'windowEnd', (extract(epoch FROM $2::timestamptz)*1000)::bigint,
   'sort', $9::text, 'effectiveSort', CASE WHEN v.complete = v.expected THEN $9::text ELSE 'name' END,
   'maxObservationCount', CASE WHEN v.complete = v.expected THEN coalesce(p.maximum, 0) END,
   'observerTypes', (SELECT coalesce(jsonb_agg(t.observer_type ORDER BY t.observer_type), '[]'::jsonb) FROM (SELECT DISTINCT observer_type FROM candidates WHERE observer_type IS NOT NULL AND observer_type <> '') t),
   'coverage', jsonb_build_object('status', CASE WHEN v.complete = v.expected THEN 'complete' WHEN v.complete > 0 OR v.partial > 0 THEN 'partial' ELSE 'unavailable' END,
      'expectedHours', v.expected, 'completeHours', v.complete, 'partialHours', v.partial, 'missingHours', v.missing)
 ), p.items
FROM packed p CROSS JOIN coverage v
RETURNING id
`

type CreateObserverDirectorySnapshotParams struct {
	Column1  pgtype.Timestamptz `json:"column_1"`
	Column2  pgtype.Timestamptz `json:"column_2"`
	Column3  []string           `json:"column_3"`
	Column4  string             `json:"column_4"`
	Column5  string             `json:"column_5"`
	Column6  string             `json:"column_6"`
	Column7  string             `json:"column_7"`
	Column8  string             `json:"column_8"`
	Column9  string             `json:"column_9"`
	ID       uuid.UUID          `json:"id"`
	QueryKey []byte             `json:"query_key"`
	Column12 bool               `json:"column_12"`
}

func (q *Queries) CreateObserverDirectorySnapshot(ctx context.Context, arg CreateObserverDirectorySnapshotParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createObserverDirectorySnapshot,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.ID,
		arg.QueryKey,
		arg.Column12,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const findObserverDirectorySnapshot = `-- name: FindObserverDirectorySnapshot :one
SELECT id FROM observer_directory_snapshots WHERE query_key = $1 AND expires_at > now()
`

func (q *Queries) FindObserverDirectorySnapshot(ctx context.Context, queryKey []byte) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findObserverDirectorySnapshot, queryKey)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getObserverDirectoryPage = `-- name: GetObserverDirectoryPage :one
SELECT (metadata || jsonb_build_object(
 'snapshot', id,
 'generatedAt', (extract(epoch FROM created_at)*1000)::bigint,
 'expiresAt', (extract(epoch FROM expires_at)*1000)::bigint,
 'hasMore', jsonb_array_length(items)::bigint > $1::bigint + $2::integer,
 'nextCursor', CASE WHEN jsonb_array_length(items)::bigint > $1::bigint + $2::integer THEN $1::bigint + $2::integer END,
 'items', (SELECT coalesce(jsonb_agg(e.item ORDER BY e.ordinality), '[]'::jsonb)
           FROM jsonb_array_elements(s.items) WITH ORDINALITY e(item, ordinality)
           WHERE e.ordinality > $1::bigint AND e.ordinality <= $1::bigint + $2::integer)
))::text AS page
FROM observer_directory_snapshots s WHERE id = $3 AND expires_at > now()
`

type GetObserverDirectoryPageParams struct {
	Column1 int64     `json:"column_1"`
	Column2 int32     `json:"column_2"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) GetObserverDirectoryPage(ctx context.Context, arg GetObserverDirectoryPageParams) (string, error) {
	row := q.db.QueryRow(ctx, getObserverDirectoryPage, arg.Column1, arg.Column2, arg.ID)
	var page string
	err := row.Scan(&page)
	return page, err
}

const lockObserverDirectoryCreation = `-- name: LockObserverDirectoryCreation :one
SELECT pg_try_advisory_xact_lock(7261930284521)::boolean
`

func (q *Queries) LockObserverDirectoryCreation(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, lockObserverDirectoryCreation)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const observerDirectoryHasCapacity = `-- name: ObserverDirectoryHasCapacity :one
SELECT count(*) < 1024 AS available FROM observer_directory_snapshots
`

func (q *Queries) ObserverDirectoryHasCapacity(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, observerDirectoryHasCapacity)
	var available bool
	err := row.Scan(&available)
	return available, err
}

const observerDirectoryWithinBudget = `-- name: ObserverDirectoryWithinBudget :one
SELECT coalesce(sum(pg_column_size(items)::bigint + pg_column_size(metadata)), 0) <= 134217728 AS available
FROM observer_directory_snapshots
`

func (q *Queries) ObserverDirectoryWithinBudget(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, observerDirectoryWithinBudget)
	var available bool
	err := row.Scan(&available)
	return available, err
}

const pruneObserverDirectorySnapshots = `-- name: PruneObserverDirectorySnapshots :exec
DELETE FROM observer_directory_snapshots WHERE expires_at <= now()
`

func (q *Queries) PruneObserverDirectorySnapshots(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneObserverDirectorySnapshots)
	return err
}
