// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signal.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSignalStats = `-- name: GetSignalStats :many
WITH readings AS (
    SELECT heard_at, snr, rssi FROM packet_observations
    WHERE heard_at >= $1::timestamptz AND heard_at < $2::timestamptz
      AND COALESCE(cardinality($3::bpchar[]), 0) = 0
    UNION ALL
    SELECT heard_at, snr, rssi FROM packet_observations
    WHERE heard_at >= $1::timestamptz AND heard_at < $2::timestamptz
      AND cardinality($3::bpchar[]) > 0 AND iata = ANY($3::bpchar[])
), samples AS (
    SELECT heard_at,
           CASE WHEN NOT (COALESCE(rssi, 0) = 0 AND COALESCE(snr, 0) = 0)
                      AND snr > '-Infinity'::real AND snr < 'Infinity'::real
                THEN snr::double precision END AS snr,
           CASE WHEN NOT (COALESCE(rssi, 0) = 0 AND COALESCE(snr, 0) = 0)
                THEN rssi::double precision END AS rssi
    FROM readings
), binned AS (
    SELECT date_trunc('hour', heard_at, 'UTC') AS hour, snr, rssi,
           width_bucket(snr, -30, 30, 12) AS snr_bin,
           width_bucket(rssi, -140, 0, 14) AS rssi_bin
    FROM samples
)
SELECT grouping(hour, snr_bin, rssi_bin)::integer AS kind,
       COALESCE(hour, 'epoch'::timestamptz)::timestamptz AS hour,
       COALESCE(snr_bin, -1)::integer AS snr_bin,
       COALESCE(rssi_bin, -1)::integer AS rssi_bin,
       count(*)::bigint AS receptions,
       count(snr)::bigint AS snr_samples,
       COALESCE(avg(snr), 0)::double precision AS snr_average,
       count(rssi)::bigint AS rssi_samples,
       COALESCE(avg(rssi), 0)::double precision AS rssi_average
FROM binned
GROUP BY GROUPING SETS ((), (hour), (snr_bin), (rssi_bin))
ORDER BY kind, hour, snr_bin, rssi_bin
`

type GetSignalStatsParams struct {
	Since pgtype.Timestamptz `json:"since"`
	Until pgtype.Timestamptz `json:"until"`
	Iatas []string           `json:"iatas"`
}

type GetSignalStatsRow struct {
	Kind        int32              `json:"kind"`
	Hour        pgtype.Timestamptz `json:"hour"`
	SnrBin      int32              `json:"snr_bin"`
	RssiBin     int32              `json:"rssi_bin"`
	Receptions  int64              `json:"receptions"`
	SnrSamples  int64              `json:"snr_samples"`
	SnrAverage  float64            `json:"snr_average"`
	RssiSamples int64              `json:"rssi_samples"`
	RssiAverage float64            `json:"rssi_average"`
}

// One reception scan supplies totals, hourly means, and two independent histograms.
// The zero/zero pair is Beacon's existing unavailable-reading sentinel. A real
// zero SNR with nonzero RSSI remains valid. Non-finite SNR never reaches JSON.
// Separate global/filtered branches retain index use after pgx adopts a generic
// prepared plan. Match the indexed bpchar column without casting each stored IATA.
func (q *Queries) GetSignalStats(ctx context.Context, arg GetSignalStatsParams) ([]GetSignalStatsRow, error) {
	rows, err := q.db.Query(ctx, getSignalStats, arg.Since, arg.Until, arg.Iatas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSignalStatsRow{}
	for rows.Next() {
		var i GetSignalStatsRow
		if err := rows.Scan(
			&i.Kind,
			&i.Hour,
			&i.SnrBin,
			&i.RssiBin,
			&i.Receptions,
			&i.SnrSamples,
			&i.SnrAverage,
			&i.RssiSamples,
			&i.RssiAverage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
